# identifiers.org Satellite docker-compose based cloud deployment
# Author: Manuel Bernal Llinares <mbdebian@gmail.com>
version: "3"
services:
    metadata:
        image: identifiersorg/cloud-ws-metadata:1.0.1
        environment:
            - WS_METADATA_CONFIG_RESOLVER_HOST=resolver
            - WS_METADATA_CONFIG_RESOLVER_PORT=8080
            - WS_METADATA_JVM_MEMORY_MAX=1024m
        ports:
            - 8082:8082
        depends_on:
            - resolver
