# identifiers.org Satellite docker-compose based cloud deployment
# Author: Manuel Bernal Llinares <mbdebian@gmail.com>
version: "3"
services:
    metadata:
        image: identifiersorg/cloud-ws-metadata:1.0.1
        environment:
            - WS_METADATA_CONFIG_RESOLVER_HOST=resolver
            - WS_METADATA_CONFIG_RESOLVER_PORT=8080
            - WS_METADATA_JVM_MEMORY_MAX=1024m
        ports:
            - "8082:8082"
        depends_on:
            - resolver
    registry:
        image: identifiersorg/cloud-ws-registry:1.0.1
        environment:
            - WS_REGISTRY_CONFIG_RESOLVER_HOST=resolver
            - WS_REGISTRY_CONFIG_RESOLVER_PORT=8080
            - WS_REGISTRY_CONFIG_EMAIL_HOST=fakesmtp
            - WS_REGISTRY_CONFIG_EMAIL_PORT=25
            - WS_REGISTRY_CONFIG_EMAIL_USERNAME=nousername
            - WS_REGISTRY_CONFIG_EMAIL_PASSWORD=nopassword
            - WS_REGISTRY_CONFIG_EMAIL_TRANSPORT_PROTOCOL=smtp
            - WS_REGISTRY_CONFIG_EMAIL_BOOLEAN_SMTP_AUTH=false
            - WS_REGISTRY_CONFIG_EMAIL_BOOLEAN_START_TLS=false
            - WS_REGISTRY_CONFIG_EMAIL_BOOLEAN_DEBUG=true
            - WS_REGISTRY_CONFIG_EMAIL_FROM=test@development.env
            - WS_REGISTRY_JVM_MEMORY_MAX=1024m
        ports:
            - "8081:8081"
        depends_on:
            - resolver
            - fakesmtp
    resolver:
        image: identifiersorg/cloud-ws-resolver:1.0.3
        environment:
            - WS_RESOLVER_CONFIG_REDIS_HOST=redis
            - WS_RESOLVER_CONFIG_REDIS_PORT=6379
            - WS_RESOLVER_CONFIG_RESOURCE_RECOMMENDER_HOST=recommender
            - WS_RESOLVER_CONFIG_RESOURCE_RECOMMENDER_PORT=8083
            - WS_RESOLVER_JVM_MEMORY_MAX=1024m
        ports:
            - "8080:8080"
        depends_on:
            - redis
            - recommender
    redis:
        image: redis:4.0.8-alpine
        ports:
            - "6379:6379"
    recommender:
        image: identifiersorg/cloud-ws-resource-recommender:1.0.0
        environment:
            - WS_RESOURCE_RECOMMENDER_JVM_MEMORY_MAX=1024m
        ports:
            - "8083:8083"
    fakesmtp:
        image: digiplant/fake-smtp
        ports:
            - "1025:25"
        volumes:
            - ./tmp/fakesmtp:/var/mail
